"""Add Phase V fields

Revision ID: ade64bbf2cfb
Revises: a5ae0085b97a
Create Date: 2026-02-08 23:14:54.488188

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ade64bbf2cfb'
down_revision = 'a5ae0085b97a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('reminder_at', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('is_recurring', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('todos', sa.Column('recurrence_interval', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('todos', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'tags')
    op.drop_column('todos', 'recurrence_interval')
    op.drop_column('todos', 'is_recurring')
    op.drop_column('todos', 'reminder_at')
    # ### end Alembic commands ###
