"""Add chat models properly

Revision ID: f865d6cad110
Revises: 002
Create Date: 2026-01-04 21:32:20.074637

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f865d6cad110'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop existing type if valid (to reset)
    op.execute("DROP TYPE IF EXISTS priority CASCADE")

    # 2. Create Enum with correct values (Title Case)
    # Using the values from models/todo.py: "Low", "Medium", "High"
    priority_enum = sa.Enum('Low', 'Medium', 'High', name='priority')
    priority_enum.create(op.get_bind())

    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_user_id'), 'conversation', ['user_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('todos', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=True)
               
    # 3. Alter column with explicit using clause and handling default
    # First drop default to avoid casting error
    op.alter_column('todos', 'priority', server_default=None)
    
    op.alter_column('todos', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('Low', 'Medium', 'High', name='priority'),
               existing_nullable=False,
               server_default=sa.text("'Medium'::priority"),
               postgresql_using="initcap(priority)::priority")
               
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('todos', 'priority',
               existing_type=sa.Enum('Low', 'Medium', 'High', name='priority'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'Medium'::character varying"))
    op.alter_column('todos', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_table('message')
    op.drop_index(op.f('ix_conversation_user_id'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###
