openapi: 3.0.3
info:
  title: Todo App - Todo CRUD API
  description: |
    Todo management endpoints for Phase II Todo application.
    All endpoints require authentication. Users can only access their own todos.
  version: 1.0.0
  contact:
    name: Evolution of Todo Project
    url: https://github.com/evolution-of-todo

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.todo-app.example.com
    description: Production server (TBD)

security:
  - cookieAuth: []

paths:
  /todos:
    get:
      summary: Get all todos for authenticated user
      description: |
        Retrieves all todos belonging to the authenticated user.
        Todos are ordered by creation date (most recent first).
        No pagination - all todos returned in single response.
      operationId: listTodos
      tags:
        - Todos
      responses:
        '200':
          description: List of todos (may be empty array)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TodoResponse'
              examples:
                with_todos:
                  summary: User has todos
                  value:
                    - id: 550e8400-e29b-41d4-a716-446655440000
                      user_id: 660e8400-e29b-41d4-a716-446655440001
                      title: Buy groceries
                      description: Milk, eggs, bread
                      completed: false
                      created_at: '2025-01-27T14:30:00Z'
                      updated_at: '2025-01-27T14:30:00Z'
                    - id: 770e8400-e29b-41d4-a716-446655440002
                      user_id: 660e8400-e29b-41d4-a716-446655440001
                      title: Finish project report
                      description: null
                      completed: true
                      created_at: '2025-01-26T09:15:00Z'
                      updated_at: '2025-01-27T10:00:00Z'
                empty:
                  summary: User has no todos
                  value: []
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Create a new todo
      description: |
        Creates a new todo for the authenticated user.
        The user_id is automatically set from the session (not from request body).
      operationId: createTodo
      tags:
        - Todos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoCreateRequest'
            examples:
              with_description:
                summary: Todo with description
                value:
                  title: Buy groceries
                  description: Milk, eggs, bread, cheese
              without_description:
                summary: Todo without description
                value:
                  title: Call dentist
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoResponse'
              examples:
                created:
                  value:
                    id: 550e8400-e29b-41d4-a716-446655440000
                    user_id: 660e8400-e29b-41d4-a716-446655440001
                    title: Buy groceries
                    description: Milk, eggs, bread, cheese
                    completed: false
                    created_at: '2025-01-27T14:30:00Z'
                    updated_at: '2025-01-27T14:30:00Z'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                empty_title:
                  value:
                    error: Validation failed
                    details: Title cannot be empty
                title_too_long:
                  value:
                    error: Validation failed
                    details: Title must be 200 characters or less
                description_too_long:
                  value:
                    error: Validation failed
                    details: Description must be 2000 characters or less
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /todos/{id}:
    get:
      summary: Get a specific todo by ID
      description: |
        Retrieves a single todo by ID.
        Returns 404 if todo doesn't exist or doesn't belong to authenticated user.
      operationId: getTodoById
      tags:
        - Todos
      parameters:
        - $ref: '#/components/parameters/TodoIdParam'
      responses:
        '200':
          description: Todo found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoResponse'
              examples:
                found:
                  value:
                    id: 550e8400-e29b-41d4-a716-446655440000
                    user_id: 660e8400-e29b-41d4-a716-446655440001
                    title: Buy groceries
                    description: Milk, eggs, bread
                    completed: false
                    created_at: '2025-01-27T14:30:00Z'
                    updated_at: '2025-01-27T14:30:00Z'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Todo not found or doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                not_found:
                  value:
                    error: Todo not found
                    details: No todo found with the specified ID
        '500':
          $ref: '#/components/responses/InternalServerError'

    put:
      summary: Update a todo's title and/or description
      description: |
        Updates the title and/or description of an existing todo.
        The updated_at timestamp is automatically updated.
        Returns 404 if todo doesn't exist or doesn't belong to authenticated user.
      operationId: updateTodo
      tags:
        - Todos
      parameters:
        - $ref: '#/components/parameters/TodoIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoUpdateRequest'
            examples:
              update_both:
                summary: Update title and description
                value:
                  title: Buy groceries and supplies
                  description: Milk, eggs, bread, cheese, paper towels
              update_title_only:
                summary: Update title only
                value:
                  title: Buy groceries (updated)
                  description: Milk, eggs, bread
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoResponse'
              examples:
                updated:
                  value:
                    id: 550e8400-e29b-41d4-a716-446655440000
                    user_id: 660e8400-e29b-41d4-a716-446655440001
                    title: Buy groceries and supplies
                    description: Milk, eggs, bread, cheese, paper towels
                    completed: false
                    created_at: '2025-01-27T14:30:00Z'
                    updated_at: '2025-01-27T15:45:00Z'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                empty_title:
                  value:
                    error: Validation failed
                    details: Title cannot be empty
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Todo not found or doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                not_found:
                  value:
                    error: Todo not found
                    details: No todo found with the specified ID
        '500':
          $ref: '#/components/responses/InternalServerError'

    delete:
      summary: Delete a todo
      description: |
        Permanently deletes a todo.
        Returns 404 if todo doesn't exist or doesn't belong to authenticated user.
        No soft delete - deletion is permanent.
      operationId: deleteTodo
      tags:
        - Todos
      parameters:
        - $ref: '#/components/parameters/TodoIdParam'
      responses:
        '204':
          description: Todo deleted successfully (no content)
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Todo not found or doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                not_found:
                  value:
                    error: Todo not found
                    details: No todo found with the specified ID
        '500':
          $ref: '#/components/responses/InternalServerError'

  /todos/{id}/toggle:
    patch:
      summary: Toggle todo completion status
      description: |
        Toggles the completed status of a todo (true ↔ false).
        The updated_at timestamp is automatically updated.
        Returns 404 if todo doesn't exist or doesn't belong to authenticated user.
      operationId: toggleTodoCompletion
      tags:
        - Todos
      parameters:
        - $ref: '#/components/parameters/TodoIdParam'
      responses:
        '200':
          description: Todo completion status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoResponse'
              examples:
                toggled_to_complete:
                  summary: Marked as complete
                  value:
                    id: 550e8400-e29b-41d4-a716-446655440000
                    user_id: 660e8400-e29b-41d4-a716-446655440001
                    title: Buy groceries
                    description: Milk, eggs, bread
                    completed: true
                    created_at: '2025-01-27T14:30:00Z'
                    updated_at: '2025-01-27T16:00:00Z'
                toggled_to_incomplete:
                  summary: Marked as incomplete
                  value:
                    id: 550e8400-e29b-41d4-a716-446655440000
                    user_id: 660e8400-e29b-41d4-a716-446655440001
                    title: Buy groceries
                    description: Milk, eggs, bread
                    completed: false
                    created_at: '2025-01-27T14:30:00Z'
                    updated_at: '2025-01-27T16:30:00Z'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: Todo not found or doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                not_found:
                  value:
                    error: Todo not found
                    details: No todo found with the specified ID
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: todo_session
      description: Session cookie from Better Auth

  parameters:
    TodoIdParam:
      name: id
      in: path
      required: true
      description: UUID of the todo
      schema:
        type: string
        format: uuid
      example: 550e8400-e29b-41d4-a716-446655440000

  schemas:
    TodoCreateRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Todo title (required, 1-200 characters)
          example: Buy groceries
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Optional detailed description (max 2000 characters)
          example: Milk, eggs, bread, cheese

    TodoUpdateRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Updated todo title (required, 1-200 characters)
          example: Buy groceries and supplies
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Updated description (max 2000 characters, can be null)
          example: Milk, eggs, bread, cheese, paper towels

    TodoResponse:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique todo identifier
          example: 550e8400-e29b-41d4-a716-446655440000
        user_id:
          type: string
          format: uuid
          description: Owner's user ID
          example: 660e8400-e29b-41d4-a716-446655440001
        title:
          type: string
          maxLength: 200
          description: Todo title
          example: Buy groceries
        description:
          type: string
          maxLength: 2000
          nullable: true
          description: Optional detailed description
          example: Milk, eggs, bread, cheese
        completed:
          type: boolean
          description: Completion status
          example: false
        created_at:
          type: string
          format: date-time
          description: Creation timestamp (ISO 8601)
          example: '2025-01-27T14:30:00Z'
        updated_at:
          type: string
          format: date-time
          description: Last modification timestamp (ISO 8601)
          example: '2025-01-27T14:30:00Z'

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Brief user-friendly error message
          example: Todo not found
        details:
          type: string
          description: Optional detailed error information
          example: No todo found with the specified ID

  responses:
    UnauthorizedError:
      description: Not authenticated or session expired
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            not_authenticated:
              value:
                error: Not authenticated
                details: No active session found

    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            server_error:
              value:
                error: Internal server error
                details: An unexpected error occurred

tags:
  - name: Todos
    description: Todo CRUD operations (Create, Read, Update, Delete, Toggle)
